services:
  - docker

branches:
  only:
    - master

os:
  - linux

env:
  global:
    - DATE=`TZ=America/New_York date "+%Y-%m-%d-%H%M"`
    - DOCKER_IMAGE="leanda/microscopy-metadata"
    - DOCKER_TESTS_IMAGE="leanda/microscopy-metadata-tests"

script:
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker build -t $DOCKER_TESTS_IMAGE:latest -f tests/Leanda.Microscopy.Metadata.Tests/Dockerfile .
  - yes | cp -rf tests/Leanda.Microscopy.Metadata.Tests/.env.travis-ci tests/Leanda.Microscopy.Metadata.Tests/.env
  - cd tests/Leanda.Microscopy.Metadata.Tests && docker-compose up --abort-on-container-exit

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE # Pushes both date and latest
